### ISSUE TITLE
Fix profile get_guardian method address match for UK site

### ISSUE THREAD

**Issue by ozPop** [ozPop/WTS-Reader-cli-gem#7]
the correct site is newsguardian.co.uk

**Comment by blazeiburgess** [comment]
I think `newsguardian.co.uk` is a different, unaffiliated site dealing with local news.

When I looked at theguardian page, it seems to route traffic to US, International, or UK automatically and doesn't change from `.com` to `.co.uk` as I originally assumed it did. 

I've taken out that regex match altogether and it should work fine from here
